# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9608ce688b0a65068b42d9fbfbe0b6520789514cbfd96aeb347709ba4d03bb679fe4bcd01aaa2b9b604581fd1545ae8dbe1ac5222f1b808697abeee23e6156
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 5f05db0e76c46611735cf8701c3fc060a1264dcde44b402752f4456de9ac0fd95f5924ceb6dd9254fb16b952f4703269f3d4fbfc5e6705855461f557b5e09cd6
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

